spring.application.name=InnerVoiceProject

spring.datasource.url=jdbc:mysql://localhost:3306/INNERVOICE
spring.datasource.username=root
spring.datasource.password=Frank@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true